- name: Deploy mckinsey apros
  hosts: all
  sudo: True
  gather_facts: True
  roles:
    - aws
    - role: automated
      AUTOMATED_USERS: "{{ EDXAPP_AUTOMATED_USERS | default({}) }}"
    - role: nginx
      nginx_sites:
      - lms
      - cms
      nginx_default_sites:
      - lms
    - role: mckinsey_apros
    - { role: 'edxapp', celery_worker: True }
    - edxapp
    - role: datadog
      when: COMMON_ENABLE_DATADOG
    - role: splunkforwarder
      when: COMMON_ENABLE_SPLUNKFORWARDER
    - role: newrelic_infrastructure
      when: COMMON_ENABLE_NEWRELIC_INFRASTRUCTURE
    - role: threatstack
      when: THREATSTACK_LICENSE_KEY is defined
    - role: datadog-uninstall
      when: not COMMON_ENABLE_DATADOG
