# Creates initial state for a master's integration environment sandbox

- name: setup master's integration environment
  hosts: all
  become: True
  gather_facts: True
  vars:
    - env_path: /edx/app/edxapp/edxapp_env
    - edxapp_venv_dir: /edx/app/edxapp/venvs/edxapp
    - edxapp_code_dir: "/edx/app/edxapp/edx-platform"

  tasks:
    - name: create lms user
      shell: . {{ env_path }} && {{ edxapp_venv_dir }}/bin/python manage.py lms manage_user {{username}} {{email}}
      args:
        chdir: "{{ edxapp_code_dir }}"

    - name: create user api access request
      shell: >
        . {{ env_path }} && {{ edxapp_venv_dir }}/bin/python manage.py lms create_api_access_request {{username}}
        --reason {{reason}} --website {{website}} --create-config
      args:
        chdir: "{{ edxapp_code_dir }}"

    - name: cache programs
      shell: . {{ env_path }} && {{ edxapp_venv_dir }}/bin/python manage.py lms cache_programs
      args:
        chdir: "{{ edxapp_code_dir }}"

    - name: create registrar orgranization
      shell: >
        . {{ env_path }} && {{ registrar_venv_dir }}/bin/python manage.py create_organization {{organization_key}}
        --group {{registrar_role}}

    - name: create registrar user
      shell: >
        . {{ env_path }} && {{ registrar_venv_dir }}/bin/python manage.py create_user {{username}} --email {{email}}
        --groups {{organization_key}}_{{registrar_role}}

