# Creates initial state for a master's integration environment sandbox

- name: setup master's integration environment
  hosts: all
  become: True
  gather_facts: True
  vars:
    - env_path: /edx/app/edxapp/edxapp_env
    - edxapp_venv_dir: /edx/app/edxapp/venvs/edxapp
    - edxapp_code_dir: "/edx/app/edxapp/edx-platform"
    - registrar_code_dir: "/edx/app/registrar/registrar"

  tasks:
    - name: create lms user
      shell: . {{ env_path }} && {{ edxapp_venv_dir }}/bin/python manage.py lms manage_user {{username}} {{email}}
      shell: . /edx/app/edxapp/edxapp_env && /edx/app/edxapp/venvs/edxapp/bin/python manage.py lms manage_user spongebob zhancock@edx.org 
      args:
        chdir: "{{ edxapp_code_dir }}"

    - name: create user api access request
      shell: >
        . {{ env_path }} && {{ edxapp_venv_dir }}/bin/python manage.py lms create_api_access_request {{username}}
        --reason {{reason}} --website {{website}} --create-config
      args:
        chdir: "{{ edxapp_code_dir }}"

    - name: create dot application
      shell: >
        . {{ env_path }} && {{ edxapp_venv_dir }}/bin/python manage.py lms create_dot_application "master's api client" {{username}}
        --client_id {{organization_key}}-api-client-id --scopes=user_id
      args:
        chdir: "{{ edxapp_code_dir }}"

    - name: create LMS catalog integration
      shell: >
        . {{ env_path }} && {{ edxapp_venv_dir }}/bin/python manage.py create_catalog_integrations --enabled --internal_api_url https://example.com/api
        --service_username discovery_worker
      args:
        chdir: "{{ edxapp_code_dir }}"

    - name: cache programs
      shell: . {{ env_path }} && {{ edxapp_venv_dir }}/bin/python manage.py lms cache_programs
      args:
        chdir: "{{ edxapp_code_dir }}"

    # - name: create registrar orgranization
    #   shell: >
    #     . {{ env_path }} && {{ registrar_venv_dir }}/bin/python manage.py create_organization {{organization_key}}
    #     --group {{registrar_role}}
    #   args:
    #     chdir: "{{ registrar_code_dir }}"

    # - name: create registrar user
    #   shell: >
    #     . {{ env_path }} && {{ registrar_venv_dir }}/bin/python manage.py create_user {{username}} --email {{email}}
    #     --groups {{organization_key}}_{{registrar_role}}
    #   args:
    #     chdir: "{{ registrar_code_dir }}"
